### PR TITLE
docs(README): correct importLazyGroup method name

### LINKED ISSUE #37: Wrong method name in README.md
The method used to import a group lazily is misspelled in the documentation:

> Then apply the LazyImportsMixin mixin (or LazyImportsBehavior) to your element and call the this.**lazyImportGroup**('group-name') method when you want to load code for that group, e.g. when the user navigates to a new page in your app. The **lazyImportGroup** method returns a Promise that resolves once the imports have finished loading and executing.

The actual name is **importLazyGroup**.

### PR DESCRIPTION
**Pull request by jlsanchezsanz**
Fixes #37

### CODE REVIEW

**Review by stramel — APPROVED** [review]
LGTM

**Comment by stramel** [comment]
Ping @rictic @justinfagnani

**Comment by stramel** [comment]
Friendly ping again @justinfagnani @rictic

**Comment by stramel** [comment]
@rictic can you take a look at this one too?

**Review by rictic — APPROVED** [review]

**Comment by stramel** [comment]
Thanks @jlsanchezsanz for the fix! 

Also, thanks @rictic for the merge!

**Pull request merged**
